### ISSUE TITLE
Allow `const` use with `'use strict'` is the first line in the file

### ISSUE THREAD

**Issue by Robdel12** [cowboyd/eslint-plugin-prefer-let#8] opened 2018-10-03 15:18 UTC
Given this:
```js
"use strict";

const MyPackage = require("the-package");
```

it shouldn't give me an eslint error, but currently does.

**Comment by cowboyd** [comment] 2018-10-22 16:57
🤔 That's odd. It must mean, than the check for `isTopLevelScope` is failing here https://github.com/cowboyd/eslint-plugin-prefer-let/blob/master/lib/rules/prefer-let.js#L58

**Comment by macklinu** [comment] 2018-11-29 01:05
I'm not able to reproduce this locally on master (912d33dd2696a2219cd7fc72409245b48bf683f6) with a unit test. The following test passes.

```diff
diff --git a/tests/lib/rules/prefer-let.js b/tests/lib/rules/prefer-let.js
index f3ea0d4..71d1abd 100644
--- a/tests/lib/rules/prefer-let.js
+++ b/tests/lib/rules/prefer-let.js
@@ -28,6 +28,9 @@ var ruleTester = new RuleTester();
 ruleTester.run("prefer-let", rule, {
 
   valid: [
+    {
+      code: `'use strict'; const MyPackage = require('the-package');`
+    },
     {
       code: "const PI = 3.14;"
     },

```

@Robdel12 are you still experiencing this error? If so, what is the error message you are seeing?

**Comment by cowboyd** [comment] 2021-10-27 22:16
Closing this as it has moved to https://github.com/thefrontside/javascript

**Closed as completed by cowboyd** 2021-10-27 22:16 UTC
